config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Using high_voltage gem for static landing pages
  root to: "homes#show"
  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

  resources :topics do
    resources :bookmarks
  end

  resources :users, only: [:update]
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :bookmarks
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :set_topic

  respond_to :html, except: [:destroy]

  def index
    @bookmarks = @topic.bookmarks.all
    respond_with(@bookmarks)
  end

  def show
    respond_with(@bookmark)
  end

  def new
    @bookmark = Bookmark.new
    respond_with(@bookmark)
  end

  def edit
  end

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @bookmark.topic = @topic
    if @bookmark.save
      # Tell the user it saved
    else
      # Tell the user there was an error
    end
    respond_with(@topic, @bookmark)
  end

  def update
    @bookmark.update(bookmark_params)
    respond_with(@topic, @bookmark)
  end

  def destroy
    @bookmark.destroy
    respond_to do |format|
      # TODO: I'm following the pattern I've seen elsewhere, but I don't actually know why there needs to be an html format listed here if we're not using it...
      format.html
      format.js
    end
  end

  private
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def bookmark_params
      params.require(:bookmark).permit(:url, :name, :user_id, :topic_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    path = current_user ? topics_path : pages_home_path
    redirect_to path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @topics = Topic.all
    respond_with(@topics)
  end

  def show
    respond_with(@topic)
  end

  def new
    @topic = Topic.new
    respond_with(@topic)
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save
    respond_with(@topic)
  end

  def update
    @topic.update(topic_params)
    respond_with(@topic)
  end

  def destroy
    @topic.destroy
    respond_with(@topic)
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      render "devise/registrations/edit"
    end
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_filter :authenticate_user!

  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = nil)
    if title
      "#{title} | #{app_name}"
    else
      app_name
    end
  end

  def bootstrap_flash(key)
    {"notice" => "success", "error" => "danger", "alert" => "warning"}.fetch(key)
  end

  def app_name
    "Blocmarks"
  end

  def company_name
    "Stephen Mariano Cabrera"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_footer.html.haml
%footer.footer
  %p
    &copy;
    = company_name
    = Time.now.strftime("%Y")

app/views/application/_nav.html.erb
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation">
            <% if current_user %>
              <% #Only neccessary so that nav_lynx will correctly render the tab as highlighted %>
              <%= nav_link_to 'Home', topics_path, {}, {:wrapper => 'li'} %>
            <% else %>
              <%= nav_link_to 'Home', root_path, {}, {:wrapper => 'li'} %>
            <% end %>
          </li>

          <li role="presentation">
            <%= nav_link_to 'About', page_path('about'), {}, {:wrapper => 'li'} %>
          </li>

          <li role="presentation">
            <% if current_user %>
              <%= link_to edit_user_registration_path, class: "btn" do %>
                <span class="glyphicon glyphicon-user"> Settings</span>
              <% end %>
            <% end %>
          </li>

          <li>
            <% if current_user %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn', id: "signout"  do %>
                <span class="glyphicon glyphicon-log-out">
                  Logout
                </span>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "btn" do %>
                <span class="glyphicon glyphicon-log-in">
                  Login
                </span>
              <% end %>
            <% end %>
          </li>
        </ul>

      </nav>
      <%= link_to  root_path do %>
        <h3 class="text-muted">
          <%= app_name %>
        </h3>
      <% end %>
    </div>

app/views/application/_notices.html.haml
- flash.each do |key, value|
  .alert{ :class => "alert-#{bootstrap_flash(key)}" }
    %button.close{ :type => "button", :data => { :dismiss => "alert" } } x
    %strong
      = value

app/views/bookmarks/_form.html.haml
= form_for [topic, bookmark] do |f|
  - if bookmark.errors.any?
    #error_explanation
      %h2= "#{pluralize(bookmark.errors.count, "error")} prohibited this bookmark from being saved:"
      %ul
        - bookmark.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :url
    = f.text_field :url, class: "form-control"
  .field.form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions
    = f.submit 'Save'

app/views/bookmarks/destroy.html.erb
You just destroyed something!

app/views/bookmarks/destroy.js.erb
<% if @bookmark.destroyed? %>
  $('#bookmark' + <%= @bookmark.id %>).hide();
<% else %>
    // Add an error message to the dom based on failure
<% end %>

app/views/bookmarks/edit.html.haml
%h1 Editing bookmark

= render :partial => 'form', :locals => {:topic => @topic, :bookmark => @bookmark }

= link_to 'Show', [@topic, @bookmark]
\|
= link_to 'Back', topic_bookmarks_path

app/views/bookmarks/index.html.haml
%h1
  Bookmarks:
  = @topic.name

%table.table
  %thead
    %tr

      %th Url
      %th Name
      %th User
      %th Topic
      %th
      %th
      %th

  %tbody
    - @bookmarks.each do |bookmark|
      %tr{ :id => "bookmark-#{bookmark.id}" }
        %td= bookmark.url
        %td= bookmark.name
        %td= bookmark.user.name
        %td= bookmark.topic.name
        %td= link_to 'Show', topic_bookmark_path(bookmark.topic, bookmark)
        %td= link_to 'Edit', edit_topic_bookmark_path(bookmark.topic, bookmark)
        %td= link_to 'Destroy', topic_bookmark_path(bookmark.topic, bookmark), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bookmark', new_topic_bookmark_path

app/views/bookmarks/new.html.haml
%h1 New bookmark

= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark }

= link_to 'Back', topic_bookmarks_path(@topic)

app/views/bookmarks/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @bookmark.url
%p
  %b Name:
  = @bookmark.name
%p
  %b User:
  = @bookmark.user.name
%p
  %b Topic:
  = @bookmark.topic.name

= link_to 'Edit', edit_topic_bookmark_path(@topic, @bookmark)
\|
= link_to 'Back', topic_bookmarks_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag %>

    <title><%= full_title yield(:title) %></title>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'nav' %>
      <%= render partial: 'notices' %>

      <%= yield %>
      <br /><br />
      <%= render partial: 'footer' %>
    </div> <!-- /container -->
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<h3>About blocmarks</h3>
<p>
  Blocmarks is a project I built as part of bloc.io Rails Developer Apprenticeship. All the projects are built from scratch with the help of an experienced mentor. If this sounds interesting to you check out bloc and if you decide to sign up it would be awesome if you included me as a referral.
  <br /> <br />
  Bloc + bookmarks = blocmarks. Naming things is hard...
</p>

<h3>About bloc</h3>
<p>
  Bloc is an online developer bootcamp (they call it an apprenticeship) where you work one-to-one with a mentor pairing on your projects and sending your code to be reviewed. Currently they've got courses in Rails Development, Frontend Development, UX Design, iOS, and Android.
</p>

<p>
  Shameless plug--if you sign up with my share link <a href="https://www.bloc.io/?ref_token=MTI4MTY3Mg">here</a> I'll get a little referral bonus. Thanks!
</p>

<h3>About Me</h3>
<p>
  To learn more about me, check out my <a href="smcabrera.github.io">website</a> where you'll find a blog, more projects and my contact information. Follow me on stuff (github, twitter, linkedin)! Use stuff I built and tell me what could be better. I'm always open to feedback.
</p>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>

  <div class="jumbotron">
    <h1><%= app_name %></h1>
    <p class="lead">A simple link sharing app</p>
    <p>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg" %> or
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>

  <div class="row marketing">
    <div class="col-lg-6">
      <h4>Organized bookmarks! It's what's good!</h4>
      <p>Don't leave your bookmarks in a mess! Save them in categories to make them easier to find</p>
    </div>

    <div class="col-lg-6">
      <h4>Sharing! Also good!</h4>
      <p>Don't be miserly with those bookmarks! Share them with others!</p>
    </div>
  </div>

app/views/topics/_form.html.haml
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
%h1 Listing topics

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @topics.each do |topic|
      %tr
        %td= topic.name
        %td= link_to 'Show', topic_path(topic)
        %td= link_to 'Edit', edit_topic_path(topic)
        %td= link_to 'Destroy', topic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @topic.name

%ul
  - @topic.bookmarks.each do |bookmark|
    %li
      = bookmark.name
      \|
      = link_to bookmark.url

= render partial: 'bookmarks/form', locals: {:topic => @topic, :bookmark => Bookmark.new}

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path